### ISSUE TITLE
xlocale.h

### ISSUE THREAD

**Issue by maxime-esa** [OpenAADL/polyorb-hi-c#31]
Several files of the runtime include `xlocale.h`

However this file is not present in recent versions of glibc, as explained here: https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

This prevents compiling applications using pohic on any recent linux distro (e.g. debian 10)

**Comment by yoogx** [comment]
You know how much I LOVE debian ..
https://github.com/OpenAADL/polyorb-hi-c/commit/75a79b3f09bd1ab18eb871c51d695f7c331f55c3

This has been added for debian precisely .. getting rid of this nuisance
