### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by maxime-esa** [OpenAADL/polyorb-hi-c#32]
The following warnings should be fixed in the runtime:

`po_hi_transport.c`:457:66: warning: unused parameter 'task_id' [-Wunused-parameter]
`po_hi_transport.c`:457:90: warning: unused parameter 'port' [-Wunused-parameter]
`po_hi_transport.c`:526:73: warning: unused parameter 'src' [-Wunused-parameter]
`po_hi_transport.c`:526:99: warning: unused parameter 'dst' [-Wunused-parameter]
`po_hi_transport.c`:539: 100: warning: unused parameter 'p' [-Wunused-parameter]

`po_hi_semaphore.c`:39:107: warning: unused parameter 'id' [-Wunused-parameter]

`po_hi_task.c`:483:40: warning: cast between incompatible function types from 'void * (*)(void)' to 'void * (*)(void *)' [-Wcast-function-type]
     err = pthread_create (&tid, &attr, (void* (*)(void*))start_routine, arg);
                                        ^
And these in the generated code:

`activity.c` : variable "error" is set but not used

**Comment by yoogx** [comment]
Closing, this ticket is addressed by openaadl/ocarina#268
